local player = require("utility.player")
local cards_manager = require("gameplay.cards.cards_manager")
local constants = require("utility.constants")

function init(self)
	player.load()
	cards_manager.load_field()
	cards_manager.update_field_ui()

	msg.post("#interaction", "update_money_ui", {
		money = cards_manager.get_money()
	})

	window.set_listener(function(_, event, data)
		if event == window.WINDOW_EVENT_FOCUS_LOST then
			cards_manager.save_field()
			player.save()
		end
	end)

	print("init")
end

function on_message(self, message_id, message, sender)
	if message_id == hash("buy_card") then
		cards_manager.buy_card()
	end
end