local cards = require("gameplay.cards.cards_manager")

function init(self)
	cards.load_money()
	cards.create("Zero Two", vmath.vector3(650, 500, 0))
	cards.create("Sakura", vmath.vector3(1300, 500, 0))

	msg.post("#interaction", "update_money_ui", { money = cards.get_money() })
	print("init")
end

function on_message(self, message_id, message, sender)
	if message_id == hash("update_money_ui") then
		msg.post("#interaction", "update_money_ui", message)
	end
end