local cards_manager = require("gameplay.cards.cards_manager")

local constants = require("utility.constants")
local press = require("utility.press_animator")

function init(self)
	self.money_node = gui.get_node("money_text")
	self.buy_button = gui.get_node("buy_button")
	msg.post(".", "acquire_input_focus")
end

function on_message(self, message_id, message, sender)
	if message_id == hash("update_money_ui") then
		gui.set_text(self.money_node, tostring(message.money))
	end
end

function on_input(self, action_id, action)
	if action_id ~= hash("touch") then return end

	if action.pressed then
		if gui.pick_node(self.buy_button, action.x, action.y) then
			press.gui_down(self.buy_button)
		end

	elseif action.released then
		if gui.pick_node(self.buy_button, action.x, action.y) then
			press.gui_up(self.buy_button)
			
			msg.post(constants.MAIN_SCRIPT, "buy_card")
			msg.post("#interaction", "update_money_ui", { money = cards_manager.get_money() })
		end
	end
end